package com.example.auroraevents;


import android.os.Build;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents an event in the application.
 * The eventId is auto-generated by Firestore and stored in the "Events" collection.
 */
public class Event {

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private String  eventId;          // Firestore document ID (set after creation)
    private String  organizerDeviceId;
    private String  name;
    private String  description;
    private String dateTime;              // stored as "yyyy-MM-dd"
    private String registrationTimeStart; // stored as "yyyy-MM-dd HH:mm:ss"
    private String registrationTimeEnd;   // stored as "yyyy-MM-dd HH:mm:ss"
    private String  location;
    private int     capacity;         // 0 = unlimited
    private String  qrCodeData;       // String payload encoded in the QR code


    // Participant lists — each list holds device IDs (User.deviceId)
    private List<String> waitingList;     // signed up, awaiting lottery
    private List<String> selectedList;    // drawn / invited but not yet confirmed
    private List<String> attendingList;   // confirmed attendees
    private List<String> declinedList;    // invited then self declined
    private List<String> cancelledList;   // self cancelled
    private List<String> removedList;     // force removed

    /** Required no-arg constructor for Firestore deserialization */
    public Event() {
        waitingList   = new ArrayList<>();
        selectedList  = new ArrayList<>();
        attendingList = new ArrayList<>();
        declinedList  = new ArrayList<>();
        cancelledList = new ArrayList<>();
        removedList   = new ArrayList<>();
    }

    public Event(String organizerDeviceId, String name, String description,
                 LocalDateTime dateTime, LocalDateTime registrationStart,
                 LocalDateTime registrationEnd, String location, int capacity) {
        this();
        this.organizerDeviceId = organizerDeviceId;
        this.name              = name;
        this.description       = description;
        this.dateTime = dateTime.format(FORMATTER); // "yyyy-MM-dd"
        this.registrationTimeStart = registrationStart.format(FORMATTER);
        this.registrationTimeEnd   = registrationEnd.format(FORMATTER);
        this.location          = location;
        this.capacity          = capacity;
    }


    // ── Getters & Setters ──────────────────────────────────────────────────

    public String getEventId()                       { return eventId; }
    public void   setEventId(String eventId)         { this.eventId = eventId; }

    public String getOrganizerDeviceId()                             { return organizerDeviceId; }
    public void   setOrganizerDeviceId(String organizerDeviceId)     { this.organizerDeviceId = organizerDeviceId; }

    public String getName()                          { return name; }
    public void   setName(String name)               { this.name = name; }

    public String getDescription()                   { return description; }
    public void   setDescription(String description) { this.description = description; }

    public String getDateTime()                      { return dateTime; }
    public void   setDateTime(String dateTime)       { this.dateTime = dateTime; }

    public String getRegistrationTimeStart()                         { return registrationTimeStart; }
    public void   setRegistrationTimeStart(String registrationTimeStart) { this.registrationTimeStart = registrationTimeStart; }

    public String getRegistrationTimeEnd()                           { return registrationTimeEnd; }
    public void   setRegistrationTimeEnd(String registrationTimeEnd) { this.registrationTimeEnd = registrationTimeEnd; }

    public String getLocation()                      { return location; }
    public void   setLocation(String location)       { this.location = location; }

    public int    getCapacity()                      { return capacity; }
    public void   setCapacity(int capacity)          { this.capacity = capacity; }

    public String getQrCodeData()                    { return qrCodeData; }
    public void   setQrCodeData(String qrCodeData)   { this.qrCodeData = qrCodeData; }

    // Converters
    public LocalDate getDateTimeAsLocalDate() {
        return LocalDateTime.parse(dateTime, FORMATTER).toLocalDate();
    }

    public LocalDateTime getRegistrationTimeStartAsDateTime() {
        return LocalDateTime.parse(registrationTimeStart, FORMATTER);
    }

    public LocalDateTime getRegistrationTimeEndAsDateTime() {
        return LocalDateTime.parse(registrationTimeEnd, FORMATTER);
    }

    public List<String> getAttendingList()                             { return attendingList; }
    public void         setAttendingList(List<String> attendingList)   { this.attendingList = attendingList; }

    public List<String> getSelectedList()                              { return selectedList; }
    public void         setSelectedList(List<String> selectedList)     { this.selectedList = selectedList; }

    public List<String> getWaitingList()                               { return waitingList; }
    public void         setWaitingList(List<String> waitingList)       { this.waitingList = waitingList; }

    public List<String> getDeclinedList()                              { return declinedList; }
    public void         setDeclinedList(List<String> declinedList)     { this.declinedList = declinedList; }

    public List<String> getRemovedList()                               { return removedList; }
    public void         setRemovedList(List<String> removedList)       { this.removedList = removedList; }

    public List<String> getCancelledList()                             { return cancelledList; }
    public void         setCancelledList(List<String> cancelledList)   { this.cancelledList = cancelledList; }
}
