package com.example.auroraevents;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import android.graphics.Bitmap;
import android.util.Log;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.journeyapps.barcodescanner.BarcodeEncoder;

/**
 * Represents an event in the application.
 * The eventId is auto-generated by Firestore and stored in the "Events" collection.
 */
public class Event {

    private String  eventId;          // Firestore document ID (set after creation)
    private String  organizerDeviceId;
    private String  name;
    private String  description;
    private Date    dateTime;
    private String  location;
    private int     capacity;         // 0 = unlimited
    private String  qrCodeData;       // String payload encoded in the QR code
    private Bitmap qR; 
  
    // Participant lists — each list holds device IDs (User.deviceId)
    private List<String> waitingList;     // signed up, awaiting lottery
    private List<String> selectedList;    // drawn / invited but not yet confirmed
    private List<String> attendingList;   // confirmed attendees
    private List<String> declinedList;    // invited then self declined
    private List<String> cancelledList;   // self cancelled
    private List<String> removedList;     // force removed

    /** Required no-arg constructor for Firestore deserialization */
    public Event() {
        waitingList   = new ArrayList<>();
        selectedList  = new ArrayList<>();
        attendingList = new ArrayList<>();
        declinedList  = new ArrayList<>();
        cancelledList = new ArrayList<>();
        removedList   = new ArrayList<>();
    }

    public Event(String organizerDeviceId, String name, String description,
                 Date dateTime, String location, int capacity) {
        this();
        this.organizerDeviceId = organizerDeviceId;
        this.name              = name;
        this.description       = description;
        this.dateTime          = dateTime;
        this.location          = location;
        this.capacity          = capacity;
    }

    // ── Getters & Setters ──────────────────────────────────────────────────

    public String getEventId()                         { return eventId; }
    public void   setEventId(String eventId)           { this.eventId = eventId; }

    public String getOrganizerDeviceId()                               { return organizerDeviceId; }
    public void   setOrganizerDeviceId(String organizerDeviceId)       { this.organizerDeviceId = organizerDeviceId; }

    public String getName()                            { return name; }
    public void   setName(String name)                 { this.name = name; }

    public String getDescription()                     { return description; }
    public void   setDescription(String description)   { this.description = description; }

    public Date   getDateTime()                        { return dateTime; }
    public void   setDateTime(Date dateTime)           { this.dateTime = dateTime; }

    public String getLocation()                        { return location; }
    public void   setLocation(String location)         { this.location = location; }

    public int    getCapacity()                        { return capacity; }
    public void   setCapacity(int capacity)            { this.capacity = capacity; }

    public String getQrCodeData()                          { return qrCodeData; }
    public void   setQrCodeData(String qrCodeData)         { this.qrCodeData = qrCodeData; }

    public List<String> getAttendingList()                             { return attendingList; }
    public void         setAttendingList(List<String> attendingList)   { this.attendingList = attendingList; }

    public List<String> getSelectedList()                              { return selectedList; }
    public void         setSelectedList(List<String> selectedList)     { this.selectedList = selectedList; }

    public List<String> getWaitingList()                               { return waitingList; }
    public void         setWaitingList(List<String> waitingList)       { this.waitingList = waitingList; }

    public List<String> getDeclinedList()                              { return declinedList; }
    public void         setDeclinedList(List<String> declinedList)     { this.declinedList = declinedList; }

    public List<String> getRemovedList()                               { return removedList; }
    public void         setRemovedList(List<String> removedList)       { this.removedList = removedList; }

    public List<String> getCancelledList()                             { return cancelledList; }
    public void         setCancelledList(List<String> cancelledList)   { this.cancelledList = cancelledList; }
  
    public Bitmap       getQrCode()                                    { return this.qR; }
    // ──QR code generation ──────────────────────────────────────────────────────────────────────────────────────────
    /**
     * takes a string of data and converts to a bitmap QR code
     * The string data is defined in the constructor and using this produces a bitmap
     * that returns the value specified inside of the variable
     * @author Sean Ross
     */
    public void generateQrCode(){
        MultiFormatWriter writer = new MultiFormatWriter(); //bitmap writer
        try{
            // ideas taken from Hilal Ahmed in medium at https://ihilalahmadd.medium.com/how-to-generate-qr-code-in-android-5a2a7edf11c

            int width = 400; //these values change the width and height of the qr code
            int height = 400;

            //convert data to bit matrix
            BitMatrix matrix = writer.encode(this.eventId, BarcodeFormat.QR_CODE, width, height);

            //convert matrix to bitmap, can be used in image view
            BarcodeEncoder encoder = new BarcodeEncoder();
            qR = encoder.createBitmap(matrix);
        }
        catch (WriterException e){
            Log.e("EVENT","Error encoding QR code", e);
        }

    }

}
