package com.example.auroraevents.model;

import com.google.firebase.firestore.Exclude;

/*
*Class to store a given comment
 */
public class Comment {
    //parent id for replies, comment id generated by Firebase
    private String id;
    private String comment;
    private String userId;
    private String parentId;
    private String eventId;
    private Object timestamp;
    public Comment() {/*for firebase*/}

    /*
    * Allows for conversion from Firebase to code for the timestamp'
    * Returns a long which can then be used with dateutils
    * */
    @Exclude //so firebase will ignore
    public long getTimeStamp(){
        if (timestamp instanceof Long){
            return (long) timestamp;
        }
        return 0L; //default val, low likelyhood of being called
    }

    /*Comment Constructor*/
    public Comment(String comment, String userId, String parentId, String id, String eventId, Object timestamp){
        this.id = id;
        this.comment = comment;
        this.parentId = parentId;
        this.userId = userId;
        this.eventId = eventId;
        this.timestamp = timestamp;
    }
    /*Getter and setters--------------------------------------------*/
    public String getComment() {return comment;}
    public void setComment(String comment) {this.comment = comment;}
    public String getUserId() {return userId;}
    public void setUserId(String userId) {this.userId = userId;}
    public String getParentId() {return parentId;}
    public void setParentId(String parentId) {this.parentId = parentId;}

    public String getId() {return id;}

    public String getEventId() {return eventId;}

    public void setEventId(String eventId) {this.eventId = eventId;}
    public Object getTimestamp() {return timestamp;}
    public void setTimestamp(Object timestamp) {this.timestamp = timestamp;}
}