package com.example.auroraevents.model;

import com.google.firebase.Timestamp;
import com.google.firebase.firestore.Exclude;
import com.google.firebase.firestore.ServerTimestamp;

/**
 * Represents the comment in application
 * Id and timestamp generated by firestore
 */
public class Comment {
    //parent id for replies, comment id generated by Firebase
    private String id;
    private String comment;
    private String userId;
    private String parentId;
    private String eventId;
    @ServerTimestamp
    private Timestamp timestamp;
    private String username;
    public Comment() {/*for firebase*/}

    /**
     * Function to return date from firebase Timestamp or long
     *
     * @return A timestamp time, or a long which can be converted with dateutils
     */
    @Exclude //so firebase will ignore
    public long getTimeStampLong(){
        if (timestamp != null) {
            return ((com.google.firebase.Timestamp) timestamp).toDate().getTime();
        }
        return System.currentTimeMillis(); //default val, low likelyhood of being called

    }

    /**
     * Comment constructor
     * @param comment The contents of the content
     * @param userId The id of the user who posted
     * @param parentId The id of the comment whom its a reply to if any
     * @param id Unique id of the comment
     * @param eventId EventId the comment is connected to
     * @param timestamp The time of the comment
     */
    public Comment(String comment, String userId, String parentId, String id, String eventId, Timestamp timestamp, String username){
        this.id = id;
        this.comment = comment;
        this.parentId = parentId;
        this.userId = userId;
        this.eventId = eventId;
        this.timestamp = timestamp;
        this.username = username;
    }
    /*Getter and setters--------------------------------------------*/
    public String getComment() {return comment;}
    public void setComment(String comment) {this.comment = comment;}
    public String getUserId() {return userId;}
    public void setUserId(String userId) {this.userId = userId;}
    public String getParentId() {return parentId;}
    public void setParentId(String parentId) {this.parentId = parentId;}

    public String getId() {return id;}
    public void setId(String id){this.id = id;}

    public String getEventId() {return eventId;}

    public void setEventId(String eventId) {this.eventId = eventId;}
    public Timestamp getTimestamp() {return timestamp;}
    public void setTimestamp(Object timestamp) {
        if (timestamp instanceof Timestamp) {
            this.timestamp = (Timestamp) timestamp;
        }
    }
    public String getUsername() {return username;}
    public void setUsername(String username) {this.username = username;}
}