package com.example.auroraevents.model;


import android.os.Build;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import android.graphics.Bitmap;

import com.example.auroraevents.server.UserDb;
import com.google.firebase.firestore.Exclude;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.journeyapps.barcodescanner.BarcodeEncoder;

/**
 * Represents an event in the application.
 * The eventId is auto-generated by Firestore and stored in the "Events" collection.
 */
public class Event {

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private String  eventId;          // Firestore document ID (set after creation)
    private String  organizerDeviceId;
    private String  name;
    private String  description;
    private String dateTime;              // stored as "yyyy-MM-dd"
    private String registrationTimeStart; // stored as "yyyy-MM-dd HH:mm:ss"
    private String registrationTimeEnd;   // stored as "yyyy-MM-dd HH:mm:ss"
    private String  location;
    private int     capacity;         // 0 = unlimited
    private String  qrCodeData;       // String payload encoded in the QR code
    private Bitmap qR;

    // Participant lists — each list holds device IDs (User.deviceId)
    public RegistrationList registrationList; // for manipulating the lists

    private List<String> waitingList;     // signed up, awaiting lottery
    private List<String> selectedList;    // drawn / invited but not yet confirmed
    private List<String> attendingList;   // confirmed attendees
    private List<String> declinedList;    // invited then self declined
    private List<String> cancelledList;   // self cancelled
    private List<String> removedList;     // force removed

    /** Required no-arg constructor for Firestore deserialization */
    public Event() {
        registrationList = new RegistrationList();
    }

    public Event(String organizerDeviceId, String name, String description,
                 LocalDateTime dateTime, LocalDateTime registrationStart,
                 LocalDateTime registrationEnd, String location, int capacity) {
        this();
        this.organizerDeviceId = organizerDeviceId;
        this.name              = name;
        this.description       = description;
        this.dateTime = dateTime.format(FORMATTER); // "yyyy-MM-dd"
        this.registrationTimeStart = registrationStart.format(FORMATTER);
        this.registrationTimeEnd   = registrationEnd.format(FORMATTER);
        this.location          = location;
        this.capacity          = capacity;
    }


    // ── Getters & Setters ──────────────────────────────────────────────────

    public String getEventId()                         { return eventId; }
    public void   setEventId(String eventId)           {
        this.eventId = eventId;
        registrationList.setEventId(eventId);
    }


    public String getOrganizerDeviceId()                               { return organizerDeviceId; }
    public void   setOrganizerDeviceId(String organizerDeviceId)       { this.organizerDeviceId = organizerDeviceId; }

    public String getName()                            { return name; }
    public void   setName(String name)                 { this.name = name; }

    public String getDescription()                     { return description; }
    public void   setDescription(String description)   { this.description = description; }

    public String getDateTime()                      { return dateTime; }
    public void   setDateTime(String dateTime)       { this.dateTime = dateTime; }

    public String getRegistrationTimeStart()                         { return registrationTimeStart; }
    public void   setRegistrationTimeStart(String registrationTimeStart) { this.registrationTimeStart = registrationTimeStart; }

    public String getRegistrationTimeEnd()                           { return registrationTimeEnd; }
    public void   setRegistrationTimeEnd(String registrationTimeEnd) { this.registrationTimeEnd = registrationTimeEnd; }

    public String getLocation()                      { return location; }
    public void   setLocation(String location)       { this.location = location; }

    public int    getCapacity()                      { return capacity; }
    public void   setCapacity(int capacity)          { this.capacity = capacity; }

    public String getQrCodeData()                    { return qrCodeData; }
    public void   setQrCodeData(String qrCodeData)   { this.qrCodeData = qrCodeData; }

    // Converters
    @Exclude
    public LocalDate getDateTimeAsLocalDate() {
        return LocalDateTime.parse(dateTime, FORMATTER).toLocalDate();
    }

    @Exclude
    public LocalDateTime getRegistrationTimeStartAsDateTime() {
        return LocalDateTime.parse(registrationTimeStart, FORMATTER);
    }

    @Exclude
    public LocalDateTime getRegistrationTimeEndAsDateTime() {
        return LocalDateTime.parse(registrationTimeEnd, FORMATTER);
    }

    public Bitmap       getQrCode()                                    { return this.qR; }

    // ──QR code generation ──────────────────────────────────────────────────────────────────────────────────────────
    /**
     * takes a string of data and converts to a bitmap QR code
     * The string data is defined in the constructor and using this produces a bitmap
     * that returns the value specified inside the variable
     * @author Sean Ross
     */
    @Exclude
    public void generateQrCode(){
        MultiFormatWriter writer = new MultiFormatWriter(); //bitmap writer
        try{
            // ideas taken from Hilal Ahmed in medium at https://ihilalahmadd.medium.com/how-to-generate-qr-code-in-android-5a2a7edf11c

            int width = 400; //these values change the width and height of the qr code
            int height = 400;

            //convert data to bit matrix
            BitMatrix matrix = writer.encode(this.eventId, BarcodeFormat.QR_CODE, width, height);

            //convert matrix to bitmap, can be used in image view
            BarcodeEncoder encoder = new BarcodeEncoder();
            qR = encoder.createBitmap(matrix);
        }
        catch (WriterException e){
            Log.e("EVENT","Error encoding QR code", e);
        }
    }

    /**
     * Returns the amount of empty slots that is available in the event
     * @return
     * Amount of empty slots available
     */
    @Exclude
    public int getEmptySlotAmount() {
        return capacity - registrationList.getAttendingList().size() - registrationList.getSelectedList().size();
    }

    /**
     * Connects and fetches user objects from database using their device IDs and returns an array list of them
     * @param listOfDeviceIDs
     * The list of user's device IDs
     * @return
     * The list of user objects that were fetched with given device IDs
     */
    @Exclude
    public ArrayList<User> getUsersFromDB(List<String> listOfDeviceIDs) {
        ArrayList<User> listOfUsers = new ArrayList<User>();
        // Fetch users from database
        var ref = new Object() {
            User returnedUser;
        };
        for (String userId : listOfDeviceIDs) {
            CountDownLatch latch = new CountDownLatch(1);
            UserDb.getInstance().getUser(userId,
                    user -> {
                        ref.returnedUser = user;
                        latch.countDown();
                    },
                    e -> {
                        Log.e("Main", "Error fetching user", e);
                        latch.countDown();
                    }
            );
            try {
                assert latch.await(10, TimeUnit.SECONDS);
            } catch (InterruptedException e) {
                continue;
            }
            if (ref.returnedUser != null) {
                listOfUsers.add(ref.returnedUser);
            }
        }
        return listOfUsers;
    }

    /**
     * Gets the array list of user objects that are in the waiting list
     * @return
     * Return the array list of user objects in the waiting list
     */
    @Exclude
    public ArrayList<User> getWaitingListOfUsers() {
        return getUsersFromDB(registrationList.getWaitingList());
    }

    /**
     * Gets the array list of user objects that are in the selected list
     * @return
     * Return the array list of user objects in the selected list
     */
    @Exclude
    public ArrayList<User> getSelectedListOfUsers() {
        return getUsersFromDB(registrationList.getSelectedList());
    }

    /**
     * Gets the array list of user objects that are in the attending list
     * @return
     * Return the array list of user objects in the attending list
     */
    @Exclude
    public ArrayList<User> getAttendingListOfUsers() {
        return getUsersFromDB(registrationList.getAttendingList());
    }

    /**
     * Gets the array list of user objects that are in the declined list
     * @return
     * Return the array list of user objects in the declined list
     */
    @Exclude
    public ArrayList<User> getDeclinedListOfUsers() {
        return getUsersFromDB(registrationList.getDeclinedList());
    }

    /**
     * Gets the array list of user objects that are in the cancelled list
     * @return
     * Return the array list of user objects in the cancelled list
     */
    @Exclude
    public ArrayList<User> getCancelledListOfUsers() {
        return getUsersFromDB(registrationList.getCancelledList());
    }

    /**
     * Gets the array list of user objects that are in the removed list
     * @return
     * Return the array list of user objects in the removed list
     */
    @Exclude
    public ArrayList<User> getRemovedListOfUsers() {
        return getUsersFromDB(registrationList.getRemovedList());
    }

    /**
     * Randomly samples users in the waiting list and adds the selected ones to the selected list
     * then send notification to both the users who were selected and not
     */
    @Exclude
    public void randomSampling() {
        int amount = getEmptySlotAmount();
        List<String> waitingList = registrationList.getWaitingList();
        // There are more empty slots than there are users in waiting list: Select everyone from waiting list
        // Also do the same if the capacity = 0 (This is when there is no limit)
        if (capacity == 0 || amount >= waitingList.size()) {
            registrationList.addAllToSelectedList(waitingList);
        }
        else { // Random sampling
            Random random = new Random();
            for (int i = 0; i < amount; i++) {
                // Generate random index using the waitingList size (waiting list will shrink so this will prevent index out of bounds)
                int randomIndex = random.nextInt(waitingList.size());
                String selectedUserID = waitingList.get(randomIndex);
                registrationList.addToSelectedList(selectedUserID);
            }
        }
    }

}