package com.example.auroraevents.model;


import android.graphics.Bitmap;
import android.util.Log;

import com.google.firebase.firestore.Exclude;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.journeyapps.barcodescanner.BarcodeEncoder;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents an event in the application.
 * The eventId is auto-generated by Firestore and stored in the "Events" collection.
 */
public class Event {

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private String eventId;          // Firestore document ID (set after creation)
    private String organizerDeviceId;
    private String name;
    private String description;
    private String price;
    private String dateTime;              // stored as "yyyy-MM-dd"
    private String registrationTimeStart; // stored as "yyyy-MM-dd HH:mm:ss"
    private String registrationTimeEnd;   // stored as "yyyy-MM-dd HH:mm:ss"
    private String location;
    private String qrUrl;
    private String posterUrl;

    private boolean geolocationRequired;
    private boolean isPrivate;
    private List<String> reports;
    private double latitude;
    private double longitude;

    // Co-organizers for this event (stored as device IDs, per-event only)
    private List<String> coOrganizerDeviceIds;

    // Participant lists — each list holds device IDs (User.deviceId)
    public RegistrationList registrationList; // for manipulating the lists

    /** Required no-arg constructor for Firestore deserialization */
    public Event() {
        registrationList = new RegistrationList();
        reports = new ArrayList<>();
        coOrganizerDeviceIds = new ArrayList<>();
    }

    public Event(
            String organizerDeviceId,
            String name,
            String description,
            String price,
            LocalDateTime dateTime,
            LocalDateTime registrationStart,
            LocalDateTime registrationEnd,
            String location,
            boolean geolocationRequired,
            int waitingCapacity,
            int attendingCapacity) {
        this();
        this.organizerDeviceId     = organizerDeviceId;
        this.name                  = name;
        this.description           = description;
        this.price                 = price;
        this.dateTime              = dateTime.format(FORMATTER); // "yyyy-MM-dd"
        this.registrationTimeStart = registrationStart.format(FORMATTER);
        this.registrationTimeEnd   = registrationEnd.format(FORMATTER);
        this.location              = location;
        this.geolocationRequired   = geolocationRequired;
        this.registrationList.setWaitingCapacity(waitingCapacity);
        this.registrationList.setAttendingCapacity(attendingCapacity);
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Event event = (Event) o;
        return
                Objects.equals(getEventId(), event.getEventId()) &&
                Objects.equals(getOrganizerDeviceId(), event.getOrganizerDeviceId()) &&
                Objects.equals(getName(), event.getName()) &&
                Objects.equals(getDescription(), event.getDescription()) &&
                Objects.equals(getPrice(), event.getPrice()) &&
                Objects.equals(getDateTime(), event.getDateTime()) &&
                Objects.equals(getRegistrationTimeStart(), event.getRegistrationTimeStart()) &&
                Objects.equals(getRegistrationTimeEnd(), event.getRegistrationTimeEnd()) &&
                Objects.equals(getLocation(), event.getLocation()) &&
                getGeolocationRequired() == event.getGeolocationRequired() &&
                getNumReports() == event.getNumReports() &&
                Objects.equals(registrationList, event.registrationList)
                ;
    }

    // ── Getters & Setters ──────────────────────────────────────────────────

    public String getEventId()                         { return eventId; }
    public void   setEventId(String eventId)           {
        this.eventId = eventId;
        registrationList.setEventId(eventId);
    }


    public String getOrganizerDeviceId()                         { return organizerDeviceId; }
    public void   setOrganizerDeviceId(String organizerDeviceId) { this.organizerDeviceId = organizerDeviceId; }

    public String getName()            { return name; }
    public void   setName(String name) { this.name = name; }

    public String getDescription()                   { return description; }
    public void   setDescription(String description) { this.description = description; }

    public String getPrice()             { return price; }
    public void   setPrice(String price) { this.price = price; }

    public String getDateTime()                { return dateTime; }
    public void   setDateTime(String dateTime) { this.dateTime = dateTime; }

    public String getRegistrationTimeStart()                             { return registrationTimeStart; }
    public void   setRegistrationTimeStart(String registrationTimeStart) { this.registrationTimeStart = registrationTimeStart; }

    public String getRegistrationTimeEnd()                           { return registrationTimeEnd; }
    public void   setRegistrationTimeEnd(String registrationTimeEnd) { this.registrationTimeEnd = registrationTimeEnd; }

    public String getLocation()                { return location; }
    public void   setLocation(String location) { this.location = location; }

    public boolean getGeolocationRequired()                            { return geolocationRequired; }
    public void    setGeolocationRequired(boolean geolocationRequired) { this.geolocationRequired = geolocationRequired; }

    public boolean isPrivate()                   { return isPrivate; }
    public void    setPrivate(boolean isPrivate) { this.isPrivate = isPrivate; }

    public int  getNumReports() { return reports.size(); }

    public double getLatitude() { return latitude; }
    public void setLatitude(double latitude) { this.latitude = latitude; }

    public double getLongitude()  { return longitude; }
    public void setLongitude(double longitude) { this.longitude = longitude; }

    // ── Co-organizer helpers ───────────────────────────────────────────────

    public List<String> getCoOrganizerDeviceIds() {
        if (coOrganizerDeviceIds == null) coOrganizerDeviceIds = new ArrayList<>();
        return coOrganizerDeviceIds;
    }

    public void setCoOrganizerDeviceIds(List<String> coOrganizerDeviceIds) {
        this.coOrganizerDeviceIds = coOrganizerDeviceIds;
    }

    /**
     * Returns true if the given device ID belongs to a co-organizer of this event.
     *
     * @param deviceId The device ID to check.
     */
    @Exclude
    public boolean isCoOrganizer(String deviceId) {
        return coOrganizerDeviceIds != null && coOrganizerDeviceIds.contains(deviceId);
    }

    /**
     * Returns true if the device ID is either the primary organizer or a co-organizer
     *
     * @param deviceId The device ID to check.
     */
    @Exclude
    public boolean isOrganizerOrCoOrganizer(String deviceId) {
        return deviceId != null &&
                (deviceId.equals(organizerDeviceId) || isCoOrganizer(deviceId));
    }

    // ── Reports ────────────────────────────────────────────────────────────

    /**
     * Adds a report
     * @param userId The device ID of the user reporting the event
     * @return
     *     {@code 0}  when success
     *     {@code -1} when the user has already reported the event
     */
    public int addReport(String userId) {
        if (!reports.contains(userId)) {
            reports.add(userId);
            return 0;
        } else
            return -1;
    }

    // Converters
    @Exclude
    public LocalDate getDateTimeAsLocalDate() {
        return LocalDateTime.parse(dateTime, FORMATTER).toLocalDate();
    }

    @Exclude
    public LocalDateTime getRegistrationTimeStartAsDateTime() {
        return LocalDateTime.parse(registrationTimeStart, FORMATTER);
    }

    @Exclude
    public LocalDateTime getRegistrationTimeEndAsDateTime() {
        return LocalDateTime.parse(registrationTimeEnd, FORMATTER);
    }

    public String getPosterUrl() {
        return posterUrl;
    }

    public void setPosterUrl(String posterUrl) {
        this.posterUrl = posterUrl;
    }

    public String getQrUrl() {
        return qrUrl;
    }

    public void setQrUrl(String qrUrl) {
        this.qrUrl = qrUrl;
    }

    // ── QR code generation ─────────────────────────────────────────────────

    @Exclude
    public Bitmap generateQrCode(){
        MultiFormatWriter writer = new MultiFormatWriter();
        try{
            // ideas taken from Hilal Ahmed in medium at https://ihilalahmadd.medium.com/how-to-generate-qr-code-in-android-5a2a7edf11c

            int width = 400;
            int height = 400;

            BitMatrix matrix = writer.encode(this.eventId, BarcodeFormat.QR_CODE, width, height);

            BarcodeEncoder encoder = new BarcodeEncoder();
            return encoder.createBitmap(matrix);
        }
        catch (WriterException e){
            Log.e("EVENT","Error encoding QR code", e);
            return null;
        }

    }
}