package com.example.auroraevents.model;


import android.graphics.Bitmap;
import android.util.Log;

import com.google.firebase.firestore.Exclude;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.journeyapps.barcodescanner.BarcodeEncoder;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Represents an event in the application.
 * The eventId is auto-generated by Firestore and stored in the "Events" collection.
 */
public class Event {

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private String eventId;          // Firestore document ID (set after creation)
    private String organizerDeviceId;
    private String name;
    private String description;
    private String price;
    private String dateTime;              // stored as "yyyy-MM-dd"
    private String registrationTimeStart; // stored as "yyyy-MM-dd HH:mm:ss"
    private String registrationTimeEnd;   // stored as "yyyy-MM-dd HH:mm:ss"
    private String location;
    private boolean geolocationRequired;
    private int    capacity;              // 0 = unlimited
    private String qrCodeData;            // String payload encoded in the QR code
    private Bitmap qR;

    // Participant lists — each list holds device IDs (User.deviceId)
    public RegistrationList registrationList; // for manipulating the lists

    /** Required no-arg constructor for Firestore deserialization */
    public Event() {
        registrationList = new RegistrationList();
    }

    public Event(
            String organizerDeviceId,
            String name,
            String description,
            String price,
            LocalDateTime dateTime,
            LocalDateTime registrationStart,
            LocalDateTime registrationEnd,
            String location,
            boolean geolocationRequired,
            int capacity) {
        this();
        this.organizerDeviceId     = organizerDeviceId;
        this.name                  = name;
        this.description           = description;
        this.price                 = price;
        this.dateTime              = dateTime.format(FORMATTER); // "yyyy-MM-dd"
        this.registrationTimeStart = registrationStart.format(FORMATTER);
        this.registrationTimeEnd   = registrationEnd.format(FORMATTER);
        this.location              = location;
        this.geolocationRequired   = geolocationRequired;
        this.capacity              = capacity;
    }


    // ── Getters & Setters ──────────────────────────────────────────────────

    public String getEventId()                         { return eventId; }
    public void   setEventId(String eventId)           {
        this.eventId = eventId;
        registrationList.setEventId(eventId);
    }


    public String getOrganizerDeviceId()                         { return organizerDeviceId; }
    public void   setOrganizerDeviceId(String organizerDeviceId) { this.organizerDeviceId = organizerDeviceId; }

    public String getName()            { return name; }
    public void   setName(String name) { this.name = name; }

    public String getDescription()                   { return description; }
    public void   setDescription(String description) { this.description = description; }

    public String getPrice()           { return price; }
    public void setPrice(String price) { this.price = price; }

    public String getDateTime()                { return dateTime; }
    public void   setDateTime(String dateTime) { this.dateTime = dateTime; }

    public String getRegistrationTimeStart()                             { return registrationTimeStart; }
    public void   setRegistrationTimeStart(String registrationTimeStart) { this.registrationTimeStart = registrationTimeStart; }

    public String getRegistrationTimeEnd()                           { return registrationTimeEnd; }
    public void   setRegistrationTimeEnd(String registrationTimeEnd) { this.registrationTimeEnd = registrationTimeEnd; }

    public String getLocation()                { return location; }
    public void   setLocation(String location) { this.location = location; }

    public boolean getGeolocationRequired()                         { return geolocationRequired; }
    public void setGeolocationRequired(boolean geolocationRequired) { this.geolocationRequired = geolocationRequired; }

    public int    getCapacity()             { return capacity; }
    public void   setCapacity(int capacity) { this.capacity = capacity; }

    public String getQrCodeData()                  { return qrCodeData; }
    public void   setQrCodeData(String qrCodeData) { this.qrCodeData = qrCodeData; }

    // Converters
    @Exclude
    public LocalDate getDateTimeAsLocalDate() {
        return LocalDateTime.parse(dateTime, FORMATTER).toLocalDate();
    }

    @Exclude
    public LocalDateTime getRegistrationTimeStartAsDateTime() {
        return LocalDateTime.parse(registrationTimeStart, FORMATTER);
    }

    @Exclude
    public LocalDateTime getRegistrationTimeEndAsDateTime() {
        return LocalDateTime.parse(registrationTimeEnd, FORMATTER);
    }

    public Bitmap       getQrCode()                                    { return this.qR; }

    // ──QR code generation ──────────────────────────────────────────────────────────────────────────────────────────
    /**
     * takes a string of data and converts to a bitmap QR code
     * The string data is defined in the constructor and using this produces a bitmap
     * that returns the value specified inside the variable
     * @author Sean Ross
     */
    @Exclude
    public void generateQrCode(){
        MultiFormatWriter writer = new MultiFormatWriter(); //bitmap writer
        try{
            // ideas taken from Hilal Ahmed in medium at https://ihilalahmadd.medium.com/how-to-generate-qr-code-in-android-5a2a7edf11c

            int width = 400; //these values change the width and height of the qr code
            int height = 400;

            //convert data to bit matrix
            BitMatrix matrix = writer.encode(this.eventId, BarcodeFormat.QR_CODE, width, height);

            //convert matrix to bitmap, can be used in image view
            BarcodeEncoder encoder = new BarcodeEncoder();
            qR = encoder.createBitmap(matrix);
        }
        catch (WriterException e){
            Log.e("EVENT","Error encoding QR code", e);
        }
    }

    // ── Sampling ──────────────────────────────────────────────────
    /**
     * Returns the amount of empty slots that is available in the event
     * @return
     * Amount of empty slots available
     */
    @Exclude
    public int getEmptySlotAmount() {
        return capacity - registrationList.getAttendingList().size() - registrationList.getSelectedList().size();
    }

    /**
     * Randomly samples users in the waiting list and adds the selected ones to the selected list
     * then send notification to both the users who were selected and not
     */
    @Exclude
    public void randomSampling() {
        registrationList.randomSampling(getEmptySlotAmount(), getCapacity());
    }

}