package com.example.auroraevents.model;

import java.util.Date;

/**
 * Represents a push notification received by a device.
 * The notificationId is auto-generated by Firestore and stored in the "Notifications" collection.
 */
public class Notification {

    private String  notificationId;   // Firestore document ID (set after creation)
    private String  deviceId;         // recipient device (Settings.Secure.ANDROID_ID)
    private String  title;
    private String  body;
    private Date    timestamp;
    private boolean read;

    /** Required no-arg constructor for Firestore deserialization */
    public Notification() {}

    public Notification(String deviceId, String title, String body) {
        this.deviceId  = deviceId;
        this.title     = title;
        this.body      = body;
        this.timestamp = new Date();
        this.read      = false;
    }

    // ── Getters & Setters ──────────────────────────────────────────────────

    public String getNotificationId()                          { return notificationId; }
    public void   setNotificationId(String notificationId)     { this.notificationId = notificationId; }

    public String getDeviceId()                                { return deviceId; }
    public void   setDeviceId(String deviceId)                 { this.deviceId = deviceId; }

    public String getTitle()                                   { return title; }
    public void   setTitle(String title)                       { this.title = title; }

    public String getBody()                                    { return body; }
    public void   setBody(String body)                         { this.body = body; }

    public Date   getTimestamp()                               { return timestamp; }
    public void   setTimestamp(Date timestamp)                 { this.timestamp = timestamp; }

    public boolean isRead()                                    { return read; }
    public void    setRead(boolean read)                       { this.read = read; }

}