package com.example.auroraevents.model;

import com.google.firebase.firestore.Exclude;

import java.util.Date;

/**
 * Represents a push notification received by a device.
 * The notificationId is auto-generated by Firestore and stored in the "Notifications" collection.
 * @author Joshua Terry
 */
public class Notification {

    private String  notificationId;   // Firestore document ID (set after creation)
    private String  deviceId;         // recipient device (Settings.Secure.ANDROID_ID)
    private String  sentFromId;       // organizer's deviceId who sent this notification
    private String  eventId;          // the event this notification was sent from
    private String  title;
    private String  body;
    private Date    timestamp;
    private boolean read;

    /**
     * Resolved at runtime from the Users collection — never written to Firestore.
     * {@code @Exclude} ensures Firestore ignores this field during serialization.
     */
    @Exclude
    private String recipientName;

    /** Required no-arg constructor for Firestore deserialization */
    public Notification() {}

    public Notification(String deviceId, String sentFromId, String eventId, String title, String body) {
        this.deviceId   = deviceId;
        this.sentFromId = sentFromId;
        this.eventId    = eventId;
        this.title      = title;
        this.body       = body;
        this.timestamp  = new Date();
        this.read       = false;
    }

    // ── Getters & Setters ──────────────────────────────────────────────────

    public String getNotificationId()                          { return notificationId; }
    public void   setNotificationId(String notificationId)     { this.notificationId = notificationId; }

    public String getDeviceId()                                { return deviceId; }
    public void   setDeviceId(String deviceId)                 { this.deviceId = deviceId; }

    public String getSentFromId()                              { return sentFromId; }
    public void   setSentFromId(String sentFromId)             { this.sentFromId = sentFromId; }

    public String getEventId()                                 { return eventId; }
    public void   setEventId(String eventId)                   { this.eventId = eventId; }

    public String getTitle()                                   { return title; }
    public void   setTitle(String title)                       { this.title = title; }

    public String getBody()                                    { return body; }
    public void   setBody(String body)                         { this.body = body; }

    public Date   getTimestamp()                               { return timestamp; }
    public void   setTimestamp(Date timestamp)                 { this.timestamp = timestamp; }

    public boolean isRead()                                    { return read; }
    public void    setRead(boolean read)                       { this.read = read; }

    @Exclude
    public String getRecipientName()                           { return recipientName; }
    @Exclude
    public void   setRecipientName(String recipientName)       { this.recipientName = recipientName; }
}